server {
    listen 8080;
	server_name localhost;

    root ./www/sitio1;
    index index.html;

    error_page 400 /errors/400.html;
    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 500 /errors/500.html;
}

server {
    listen 8080;
    listen 192.168.1.89:8282;

    root ./www/sitio2;
    index index.html;

    error_page 400 /errors/400.html;
    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 500 /errors/500.html;

    location /images {
	    root ./www/images;
	    autoindex on;
	    methods GET;
	}

	location /upload {
	    methods POST;
	    upload_store ./uploads;
	}
	
	location /old {
	    return 301 /new;
	}
	

	location /cgi-bin {
	    root ./cgi-bin;
	    methods GET POST;
	    cgi .py /usr/bin/python3;
	}
	
	location /docs {
	    root ./documentation;
	    index home.html;
	}

}