server {
    listen 8080;
    server_name localhost;

    root ./www/sitio1;
}

server {
    listen 8080;
    server_name sitio2;

    root ./www/sitio2;
}

server {
    listen 8080;
    server_name sitio3;

    root ./www/sitio3;
}