
server
{
    listen 127.0.0.1:8080;
    root ./www/sitio2;
	index index.html;
    server_name interno;
}


server
{
    listen 0.0.0.0:8080;
    root ./www/sitio1;
	index index.html;
    server_name publico;
}

server
{
    listen 0.0.0.0:8282;
    root ./www/sitio1;
	index index.html;
    server_name sitio1;
}