
server
{
    listen 127.0.0.1:8080;
    root ./www/sitio2;
	index index.html;
    server_name privado;

    error_page 400 /errors/400.html;
	error_page 404 /errors/404.html;
	error_page 403 /errors/403.html;
	error_page 500 /errors/500.html;
}


server
{
    listen 0.0.0.0:8080;
    root ./www/sitio1;
	index index.html;
    server_name publico;

    error_page 400 /errors/400.html;
	error_page 404 /errors/404.html;
	error_page 403 /errors/403.html;
	error_page 500 /errors/500.html;
}

server
{
    listen 0.0.0.0:8282;
    root ./www/sitio1;
	index index.html;
    server_name publico;

    error_page 400 /errors/400.html;
	error_page 404 /errors/404.html;
	error_page 403 /errors/403.html;
	error_page 500 /errors/500.html;
}